version: '3.5'

volumes:
  database:

services:
  
  # REVERSE PROXY
  nginx:
    image: nginx
    container_name: sidp-nginx
    volumes:
    - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  # DATABASE
  postgres:
    image: postgres
    container_name: sidp-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ./initdbs.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data

  # KRATOS
  kratos-migrate:
    image: oryd/kratos
    container_name: sidp-kratos-migrate
    restart: on-failure
    command: migrate sql -e --yes
    environment:
      - DSN=postgres://$DB_USER:$DB_PASSWORD@sidp-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos:/etc/config/kratos

  kratos:
    image: oryd/kratos
    container_name: sidp-kratos
    restart: on-failure
    command: serve -c /etc/config/kratos/.kratos.yml --dev
    environment:
      - DSN=postgres://$DB_USER:$DB_PASSWORD@sidp-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos:/etc/config/kratos
    ports:
      - "4433:4433"
  
  # HYDRA
  hydra-migrate:
    image: oryd/hydra:latest-alpine
    container_name: sidp-hydra-migrate
    restart: on-failure
    environment:
      - DSN=postgres://$DB_USER:$DB_PASSWORD@sidp-postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
      
  hydra:
    image: oryd/hydra:latest-alpine
    container_name: sidp-hydra
    restart: on-failure
    ports:
      - "4445:4445"
    command: serve all --dangerous-force-http
    environment:
      - DSN=postgres://$DB_USER:$DB_PASSWORD@sidp-postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEAK_SENSITIVE_VALUES=true
      - URLS_SELF_ISSUER=http://127.0.0.1/.ory/hydra
      - URLS_SELF_PUBLIC=http://127.0.0.1/.ory/hydra
      - URLS_CONSENT=http://127.0.0.1/oauth/consent
      - URLS_LOGIN=http://127.0.0.1/oauth/login
      - URLS_LOGOUT=http://127.0.0.1/oauth/logout
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SECRETS_SYSTEM=-->>--YouReallyNeedToChangeThis--<<--
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=-->>--YouReallyNeedToChangeThis--<<--