version: '3.5'

services:

#  server:
#    build: ./server

#  frontend:
#    build: ./frontend
    
  nginx:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

# For linux  
#    extra_hosts:
#      host.docker.internal: 172.17.0.1

  # KRATOS
  kratos-postgres:
    image: postgres:9.6
    container_name: kratos-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kratos
      - POSTGRES_USER=$KRATOS_DB_USER
      - POSTGRES_PASSWORD=$KRATOS_DB_PASSWORD

  kratos-migrate:
    image: oryd/kratos
    command: migrate sql -e --yes
    environment:
      - DSN=postgres://$KRATOS_DB_USER:$KRATOS_DB_PASSWORD@kratos-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos:/etc/config/kratos

  kratos:
    image: oryd/kratos
    container_name: kratos
    command: serve -c /etc/config/kratos/.kratos.yml --dev
    environment:
      - DSN=postgres://$KRATOS_DB_USER:$KRATOS_DB_PASSWORD@kratos-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos:/etc/config/kratos