version: v0.6.3-alpha.1

serve:
  public:
    base_url: http://127.0.0.1/.ory/kratos/
    cors:
      enabled: true
      exposed_headers:
      - 'Location'
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1/
  whitelisted_return_urls:
    - http://127.0.0.1

  methods:
    password:
      enabled: true
    oidc:
      config:
        providers:
        - id: github
          provider: generic
          mapper_url: http://mydomain.com/github.schema.json
          client_id: ABCD
          client_secret: ABCD
          scope:
          - email
          issuer_url: http://openid-connect-provider/
          auth_url: http://openid-connect-provider/oauth2/auth
          token_url: http://openid-connect-provider/oauth2/token
          
  flows:
    error:
      ui_url: http://127.0.0.1/error

    settings:
      ui_url: http://127.0.0.1/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1/verify
      after:
        default_browser_return_url: http://127.0.0.1/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1/auth/login

    login:
      ui_url: http://127.0.0.1/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1/auth/register
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true